trigger:
- main

pool:
  name: default

variables:
- group: terraform-secrets   # Variable group where sql_admin_password is stored

steps:
- task: AzureCLI@2
  displayName: Terraform Init, Validate, Plan
  inputs:
    azureSubscription: terraform-connection   # REQUIRED service connection
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: terraform
    inlineScript: |
      echo "Terraform Init"
      terraform init

      echo "Terraform Validate"
      terraform validate

      echo "Terraform Plan"
      terraform plan -var-file=env/prod.tfvars

  env:
    TF_VAR_sql_admin_password: $(sql_admin_password)