trigger: none

pool:
  name: default

variables:
- group: terraform-secrets

stages:
- stage: Apply
  displayName: Terraform Apply (Prod)
  jobs:
  - deployment: TerraformApply
    environment: prod   # This enforces approval
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: Terraform Apply
            inputs:
              azureSubscription: terraform-connection
              scriptType: ps
              scriptLocation: inlineScript
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
              inlineScript: |
                terraform version
                terraform init -reconfigure
                terraform apply -var-file="env/prod.tfvars" -auto-approve
            env:
              TF_VAR_sql_admin_password: $(sql_admin_password)
              TF_VAR_ssh_public_key: $(ssh_public_key