trigger:
- main

pool:
  name: default

variables:
- group: terraform-secrets

steps:
- task: AzureCLI@2
  displayName: Terraform Init Validate Plan
  inputs:
    azureSubscription: terraform-connection
    scriptType: ps
    scriptLocation: inlineScript
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform
    inlineScript: |
      terraform version

      echo "Terraform Init"
      terraform init

      echo "Terraform Validate"
      terraform validate

      echo "Terraform Plan"
      terraform plan -out=tfplan

      terraform show -no-color tfplan > tfplan.txt

  env:
    TF_VAR_sql_admin_password: $(sql_admin_password)
    TF_VAR_ssh_public_key: $(ssh_public_key)