trigger: none

stages:
- stage: Deploy
  jobs:
  - deployment: TerraformApply
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - script: terraform init
            workingDirectory: terraform

          - script: terraform apply -auto-approve -var-file=env/prod.tfvars
            workingDirectory: terraform